import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';
import {assembleGame,activeMembership,cleanMembership,paypalURL} from '../src/game/spark.js';import {freshGame} from '../src/game/engine.js';import {missions,worlds} from '../src/game/content.js';
test('membership expires at paid-through time and invalid or client claims do not grant it',()=>{assert.equal(activeMembership({active:true,expiresAt:101},100),true);for(const m of [{active:true,expiresAt:100},{active:false,expiresAt:200},{active:true,expiresAt:'200'},{status:'paid',expiresAt:200},null])assert.equal(activeMembership(m,100),false);});
test('owner approval needs checked payment reference and future date',()=>{assert.throws(()=>cleanMembership({active:true,expiresAt:200,reference:'I-123',confirmed:false},100),/Check/);assert.throws(()=>cleanMembership({active:true,expiresAt:50,reference:'I-123',confirmed:true},100),/future/);assert.throws(()=>cleanMembership({active:true,expiresAt:200,reference:'',confirmed:true},100));assert.deepEqual(cleanMembership({active:false,expiresAt:0},100),{active:false,expiresAt:0,reference:'',note:''});});
test('PayPal checkout allows only PayPal HTTPS without embedded credentials',()=>{assert.equal(paypalURL('https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-123'),'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-123');for(const url of ['javascript:alert(1)','http://www.paypal.com/','https://paypal.com.evil.test/','https://user:password@www.paypal.com/'])assert.throws(()=>paypalURL(url));});
test('XP and rewards derive only from verified missions and defeated bosses',()=>{const profile=freshGame().profile;const g=assembleGame(profile,{m1:{status:'pending',xp:99999},m2:{status:'verified',xp:99999}},{foundation:{won:false,round:2,xp:99999}},{});assert.equal(g.xp,missions[1].xp);assert.equal(g.options.length,0);assert.equal(g.guideXp.strategist,missions[1].xp);assert.deepEqual(g.achievements,['First proof']);});
test('all worlds derive the same earned total with stable achievements after reload',()=>{const ms=Object.fromEntries(missions.map(m=>[m.id,{status:'verified'}])),bs=Object.fromEntries(worlds.map(w=>[w.id,{won:true,round:3}]));const g=assembleGame(freshGame().profile,ms,bs,{});assert.equal(g.xp,missions.reduce((s,m)=>s+m.xp,0)+worlds.reduce((s,w)=>s+300+w.index*50,0));assert.equal(g.options.length,9);assert.equal(g.achievements.filter(x=>x==='Halfway hero').length,1);assert.deepEqual(assembleGame(g.profile,ms,bs,{}),g);});
test('guide memory survives derived progress without granting guide XP for chat',()=>{const g=assembleGame(freshGame().profile,{},{},{creator:{chats:[{role:'user',text:'hello'}],memory:{answers:{audience:'gardeners'},pending:'outcome'}}});assert.equal(g.coaching.creator.answers.audience,'gardeners');assert.equal(g.chats.creator.length,1);assert.equal(g.guideXp.creator,undefined);});
test('Spark deployment has no paid Firebase runtime or AI provider dependency',async()=>{const cfg=JSON.parse(await readFile(new URL('../firebase.json',import.meta.url)));assert.equal(cfg.functions,undefined);assert.equal(cfg.storage,undefined);for(const name of ['firebase.js','backend.js']){const s=await readFile(new URL('../src/'+name,import.meta.url),'utf8');assert.doesNotMatch(s,/firebase\/(functions|storage)|httpsCallable|api\.openai\.com|OPENAI_API_KEY/);}assert.ok(!(await readdir(new URL('../',import.meta.url))).includes('functions'));});
