import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {activeMembership,activeTester} from '../src/game/spark.js';
import * as content from '../src/game/content.js';import * as engine from '../src/game/engine.js';import * as rewards from '../src/game/rewards.js';import {bossScenario} from '../src/game/coaching.js';import {training} from '../src/game/training.js';import {offlineRounds} from '../src/device.js';
const source=(await readFile(new URL('../src/main.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replaceAll('import.meta.env.BASE_URL',"'./'").replaceAll('import.meta.env.PROD','false').replaceAll('import.meta.env','({})');
const names=['Compass','Feather','Hammer','ChartNoAxesCombined','Zap','Gem','Radio','MessagesSquare','Swords','HeartHandshake','Settings','Crown','Map','ScrollText','ShieldCheck','BookOpen','UserRound','Lock','ArrowRight','Check','Flame','Shield','KeyRound','Star','Download','LogOut','Volume2','VolumeX','ChevronRight','ExternalLink','Cloud','HardDrive','RefreshCw'];
function renderScreen(route,extra={}){const app={innerHTML:''},game=engine.freshGame();const context={activeMembership,activeTester,...content,...engine,...rewards,...Object.fromEntries(names.map(n=>[n,{}])),bossScenario,training,offlineRounds,createIcons(){},api:{cloud:true,session:{game,proofs:[],user:null,ready:true,...extra},initBackend:async()=>{},watchGamerChat:()=>()=>{}},location:{hash:'#'+route},navigator:{onLine:true},window:{addEventListener(){}},document:{documentElement:{dataset:{},classList:{toggle(){}}},querySelector:s=>s==='#app'?app:null,querySelectorAll:()=>[]},localStorage:{getItem:()=>null},sessionStorage:{getItem:()=>null},console,setTimeout,clearTimeout,URL,Blob};vm.runInNewContext(source,context);return app.innerHTML;}
for(const route of ['map','unlocked','mission','guides','boss','vault','progress','resources','membership','profile','community'])test(`signed-out ${route} screen renders without a runtime exception`,()=>{const html=renderScreen(route);assert.ok(html.includes('<main'));assert.ok(html.includes('Community'));assert.ok(!html.includes('powered by LWA'));});
test('signed-in membership explains automatic payments and exposes refresh',()=>{const html=renderScreen('membership',{user:{uid:'alice',email:'alice@example.test'},membershipRequired:true,checkoutReady:true,billing:{paypalUrl:'https://www.paypal.com/',offerLabel:'Subscribe'},membershipRequest:{status:'pending'}});assert.doesNotMatch(html,/membership-request-form/);assert.match(html,/automatically/);assert.match(html,/Refresh my access/);});
test('owner sees PayPal settings and access controls while a player does not',()=>{const owner=renderScreen('admin',{user:{uid:'owner',email:'owner@example.test'},isOwner:true,billing:{requireMembership:true}});assert.match(owner,/billing-settings-form/);assert.match(owner,/Payment server HTTPS address/);assert.match(owner,/Automatic PayPal subscriptions/);const player=renderScreen('admin',{user:{uid:'alice'},isOwner:false});assert.doesNotMatch(player,/member-access-form/);assert.match(player,/Owner access only/);});
test('proof submission offers written evidence and a link without a file-upload field',()=>{const game=engine.freshGame();game.missions.m1={step:4,status:'active',draft:'A'.repeat(70)};const html=renderScreen('mission',{game,user:{uid:'alice'}});assert.match(html,/proof-form/);assert.match(html,/proof-url/);assert.doesNotMatch(html,/type="file"/);});

test('tester pass shows player ID and keeps PayPal management available',()=>{const html=renderScreen('membership',{user:{uid:'tester'},tester:{active:true,expiresAt:0},entitlement:true,membership:null});assert.match(html,/Your tester pass is active/);assert.match(html,/tester<\/code>/);assert.match(html,/Manage PayPal subscription/);});
test('expired tester with stale entitlement renders without a paid membership',()=>{const html=renderScreen('membership',{user:{uid:'tester'},tester:{active:true,expiresAt:1},entitlement:true,membership:null});assert.doesNotMatch(html,/Your tester pass is active|Access through/);});
test('owner tester controls are hidden from ordinary players',()=>{assert.match(renderScreen('admin',{isOwner:true,user:{uid:'owner'}}),/tester-access-form/);assert.doesNotMatch(renderScreen('admin',{isOwner:false,user:{uid:'tester'}}),/tester-access-form/);});

test('standalone Codex never renders legacy referral resources, even when saved configuration exists',()=>{const html=renderScreen('resources',{isOwner:true,resourceAdmin:true,resources:{mainTitle:'LWA',mainUrl:'https://external-course.example',products:[{title:'Third-party course',url:'https://external-course.example'}]}});assert.match(html,/The Seed Ledger/);assert.doesNotMatch(html,/LWA|external-course|referral|resources-form/i);});

test('Proof Bank offers screenshot, journal, backup and direct device-download controls',()=>{const html=renderScreen('resources',{user:{uid:'alice'}});for(const control of ['bank-image-form','bank-note-form','data-bank-export','data-bank-local-image','data-bank-local-note'])assert.ok(html.includes(control));assert.match(html,/12 screenshot slots/);assert.match(html,/24 journal slots/);assert.doesNotMatch(html,/data-bank-empty/);});
