import {cleanBankItem,freeBankSlot} from './game/bank.js';
import publicConfig from './firebase-public.json';
import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,signOut,connectAuthEmulator} from 'firebase/auth';
import {getFirestore,Bytes,deleteDoc,doc,collection,getDoc,getDocs,setDoc,updateDoc,query,where,orderBy,limit,onSnapshot,runTransaction,writeBatch,serverTimestamp,getCountFromServer,connectFirestoreEmulator} from 'firebase/firestore';
import {freshGame,applyAction,missionState,safeText,requireThat} from './game/engine.js';
import {worlds,missions} from './game/content.js';
import {guideReply,assessBoss} from './game/coaching.js';
import {cleanChat} from './game/community.js';
import {cleanAnnouncement} from './game/admin.js';
import {equipReward,rewardCatalogue,rewardEarned} from './game/rewards.js';
import {billingApiURL,paidMembership,assembleGame,activeTester,cleanTester,activeMembership,cleanMembership,paypalURL,defaultBilling} from './game/spark.js';
let auth,db,cached=null;
const idCheck=id=>requireThat(typeof id==='string'&&/^[a-zA-Z0-9_-]{1,128}$/.test(id),'Invalid identifier.');
const uid=()=>{requireThat(auth?.currentUser,'Sign in to continue.');return auth.currentUser.uid;};
const playerRef=(id=uid())=>doc(db,'sparkPlayers',id);
const missionRef=(id,player=uid())=>doc(db,'sparkPlayers',player,'missions',id);
const bossRef=(id)=>doc(db,'sparkPlayers',uid(),'bosses',id);
const data=snap=>snap.exists()?snap.data():null;
const records=snap=>Object.fromEntries(snap.docs.map(d=>[d.id,d.data()]));
const rows=snap=>snap.docs.map(d=>({id:d.id,...d.data()}));
export async function initFirebase(){const e=import.meta.env;const app=initializeApp({apiKey:e.VITE_FIREBASE_API_KEY||publicConfig.apiKey,authDomain:e.VITE_FIREBASE_AUTH_DOMAIN||publicConfig.authDomain,projectId:e.VITE_FIREBASE_PROJECT_ID||publicConfig.projectId,storageBucket:e.VITE_FIREBASE_STORAGE_BUCKET||publicConfig.storageBucket,messagingSenderId:e.VITE_FIREBASE_MESSAGING_SENDER_ID||publicConfig.messagingSenderId,appId:e.VITE_FIREBASE_APP_ID||publicConfig.appId});auth=getAuth(app);db=getFirestore(app);if(e.VITE_USE_EMULATORS==='true'){connectAuthEmulator(auth,'http://127.0.0.1:9099');connectFirestoreEmulator(db,'127.0.0.1',8080);}}
export const watchAuth=fn=>onAuthStateChanged(auth,u=>{cached=null;fn(u);});
export const authenticate=(kind,email,password)=>kind==='signup'?createUserWithEmailAndPassword(auth,email,password):kind==='reset'?sendPasswordResetEmail(auth,email):signInWithEmailAndPassword(auth,email,password);
export const logout=()=>signOut(auth);
async function ownerOnly(){const me=uid(),owner=data(await getDoc(doc(db,'sparkConfig','owner')));requireThat(owner?.uid===me,'Owner access required.');return me;}
async function ensurePlayer(){const ref=playerRef();await runTransaction(db,async tx=>{if(!(await tx.get(ref)).exists())tx.set(ref,{profile:freshGame().profile,email:auth.currentUser.email||'',cosmetics:{},updatedAt:serverTimestamp()});});}
async function getPlayer(){const me=uid();await ensurePlayer();const [p,ms,bs,gs,proofs,member,billing,owner,announcement,request,tester,automatic]=await Promise.all([getDoc(playerRef()),getDocs(collection(db,'sparkPlayers',me,'missions')),getDocs(collection(db,'sparkPlayers',me,'bosses')),getDocs(collection(db,'sparkPlayers',me,'guides')),getDocs(query(collection(db,'sparkProofs'),where('uid','==',me),limit(100))),getDoc(doc(db,'sparkMemberships',me)),getDoc(doc(db,'sparkConfig','billing')),getDoc(doc(db,'sparkConfig','owner')),getDoc(doc(db,'appConfig','announcement')),getDoc(doc(db,'sparkMembershipRequests',me)),getDoc(doc(db,'sparkTesters',me)),getDoc(doc(db,'sparkPayPalMemberships',me))]);requireThat(auth.currentUser?.uid===me,'Account changed.');const g=assembleGame(p.data().profile,records(ms),records(bs),records(gs));g.cosmetics={};for(const r of rewardCatalogue)if(p.data().cosmetics?.[r.slot]===r.value&&rewardEarned(g,r))g.cosmetics[r.slot]=r.value;const cfg={...defaultBilling,...data(billing)};cached={game:g,proofs:rows(proofs).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)),isOwner:data(owner)?.uid===me,membership:paidMembership(data(member),data(automatic)),automaticMembership:data(automatic),billing:cfg,tester:data(tester),entitlement:!!paidMembership(data(member),data(automatic))||activeTester(data(tester)),membershipRequired:cfg.requireMembership!==false,checkoutReady:!!cfg.apiUrl,resources:null,announcement:data(announcement),membershipRequest:data(request)};return cached;}
function game(){requireThat(cached,'Reload your adventure first.');return cached.game;}
function access(world){if(world===0||cached.isOwner||cached.billing.requireMembership===false)return;requireThat(activeMembership(cached.membership)||activeTester(cached.tester),'Your access needs owner confirmation or renewal. Open Membership.');}
async function gameAction(a){
 if(a.type==='profile'){const next=applyAction(game(),a);await updateDoc(playerRef(),{profile:next.profile,updatedAt:serverTimestamp()});return;}
 if(a.type==='equip'){const next=equipReward(game(),a.rewardId);await updateDoc(playerRef(),{cosmetics:next.cosmetics,updatedAt:serverTimestamp()});return;}
 requireThat(a.type==='step','This action is not available.');const m=missions.find(m=>m.id===a.missionId);requireThat(m,'Unknown mission.');access(m.world);
 await runTransaction(db,async tx=>{const ref=missionRef(m.id),old=await tx.get(ref);const g=structuredClone(game());if(old.exists())g.missions[m.id]=old.data();const next=applyAction(g,a),s=missionState(next,m.id);tx.set(ref,{step:s.step,status:s.status,draft:s.draft||'',proofId:s.proofId||'',feedback:s.feedback||'',practiceAnswer:a.expectedStep===1?a.answer:old.data()?.practiceAnswer??-1,updatedAt:serverTimestamp()});});
}
async function submitProof({missionId,proofId,proof,attachment}){requireThat(!attachment,'Use written evidence and an HTTPS link. File uploads are not included on Spark.');const m=missions.find(m=>m.id===missionId);requireThat(m,'Unknown mission.');access(m.world);idCheck(proofId);
 await runTransaction(db,async tx=>{const ref=missionRef(m.id),old=await tx.get(ref);const g=structuredClone(game());if(old.exists())g.missions[m.id]=old.data();const next=applyAction(g,{type:'submit',missionId,proofId,proof});tx.set(doc(db,'sparkProofs',proofId),{uid:uid(),missionId,summary:proof.summary.trim(),evidence:proof.evidence.map(x=>x.trim()),url:proof.url||'',status:'pending',feedback:'',createdAt:serverTimestamp()});tx.set(ref,{...old.data(),...next.missions[m.id],updatedAt:serverTimestamp()});});
}
async function askGuide({guideId,message,reset=false}){idCheck(guideId);return runTransaction(db,async tx=>{const ref=doc(db,'sparkPlayers',uid(),'guides',guideId),old=data(await tx.get(ref));const g=structuredClone(game());g.coaching[guideId]=old?.memory||{};const reply=guideReply({game:g,guideId,message,reset});const chats=[...(old?.chats||[]),{role:'user',text:message},{role:'guide',text:reply.text}].slice(-12);tx.set(ref,{memory:{...reply.memory,question:reply.question},chats,updatedAt:serverTimestamp()});return {text:reply.text,question:reply.question,mode:'adaptive'};});}
async function battle({worldId,answer,choice,check,scenarioId,expectedRound}){const w=worlds.find(w=>w.id===worldId);requireThat(w,'Unknown world.');access(w.index);return runTransaction(db,async tx=>{const ref=bossRef(w.id),old=data(await tx.get(ref)),g=structuredClone(game());if(old)g.bosses[w.id]=old;const reply=assessBoss({game:g,world:w,answer,choice,check,scenarioId});const next=applyAction(g,{type:'boss',worldId,answer,expectedRound,passed:reply.passed,feedback:reply.feedback});tx.set(ref,{...next.bosses[w.id],lastChoice:choice,lastCheck:check,lastAnswer:answer,updatedAt:serverTimestamp()});return reply;});}
async function reviewQueue(){await ownerOnly();return rows(await getDocs(query(collection(db,'sparkProofs'),where('status','==','pending'),limit(100)))).filter(p=>p.uid!==uid());}
async function reviewProof({uid:player,proofId,approved,feedback}){const reviewer=await ownerOnly();requireThat(player!==reviewer,'You cannot review your own evidence.');idCheck(player);idCheck(proofId);safeText(feedback,10,2000);await runTransaction(db,async tx=>{const pref=doc(db,'sparkProofs',proofId),p=data(await tx.get(pref));requireThat(p?.uid===player&&p.status==='pending','Proof changed. Refresh the queue.');const mref=missionRef(p.missionId,player),m=data(await tx.get(mref));requireThat(m?.proofId===proofId&&m.status==='pending','Proof changed. Refresh the queue.');tx.update(pref,{status:approved?'verified':'rejected',feedback,reviewer,reviewedAt:serverTimestamp()});tx.update(mref,{status:approved?'verified':'active',step:approved?6:4,feedback,updatedAt:serverTimestamp()});});}

async function getAdminOverview(){await ownerOnly();const [players,proofs,requests,members,announcement,testers,automaticMembers]=await Promise.all([getCountFromServer(collection(db,'sparkPlayers')),getCountFromServer(query(collection(db,'sparkProofs'),where('status','==','pending'))),getDocs(query(collection(db,'sparkMembershipRequests'),limit(100))),getDocs(query(collection(db,'sparkMemberships'),limit(100))),getDoc(doc(db,'appConfig','announcement')),getDocs(query(collection(db,'sparkTesters'),limit(100))),getDocs(query(collection(db,'sparkPayPalMemberships'),limit(100)))]);return {automaticMembers:rows(automaticMembers),testers:rows(testers),playerCount:players.data().count,pendingProofs:proofs.data().count,announcement:data(announcement),membershipRequests:rows(requests),members:rows(members)};}
async function saveAnnouncement(a){await ownerOnly();await setDoc(doc(db,'appConfig','announcement'),{...cleanAnnouncement(a),updatedBy:uid(),updatedAt:serverTimestamp()});}
export const watchGamerChat=(next,error)=>onSnapshot(query(collection(db,'sparkChat'),orderBy('createdAt','desc'),limit(50)),s=>next(rows(s).reverse()),error);
async function sendChat({text,messageId}){const me=uid();idCheck(messageId);text=cleanChat(text);await runTransaction(db,async tx=>{const qref=doc(db,'sparkChatLimits',me),mref=doc(db,'sparkChat',messageId);const [q,m]=await Promise.all([tx.get(qref),tx.get(mref)]);if(m.exists()){requireThat(m.data().uid===me,'Invalid message ID.');return;}const last=q.data()?.sentAt?.toMillis?.()||0;requireThat(Date.now()-last>=6000,'Please wait a few seconds before sending another message.');tx.set(qref,{sentAt:serverTimestamp(),messageId});tx.set(mref,{uid:me,playerName:game().profile.name,text,createdAt:serverTimestamp(),removed:false});});}
async function reportChat({messageId,reason}){idCheck(messageId);safeText(reason,3,500);await setDoc(doc(db,'sparkReports',messageId+'_'+uid()),{messageId,reportedBy:uid(),reason,status:'open',createdAt:serverTimestamp()});}
async function moderateChat({messageId,mute}){await ownerOnly();const ref=doc(db,'sparkChat',messageId),m=data(await getDoc(ref));requireThat(m,'Message not found.');const batch=writeBatch(db);batch.update(ref,{text:'Message removed by the owner.',removed:true});if(mute)batch.set(doc(db,'sparkMutes',m.uid),{until:Date.now()+86400000});await batch.commit();}
async function getChatReports(){await ownerOnly();const reports=rows(await getDocs(query(collection(db,'sparkReports'),where('status','==','open'),limit(50))));return Promise.all(reports.map(async r=>({...r,messageText:data(await getDoc(doc(db,'sparkChat',r.messageId)))?.text||'Message unavailable'})));}
async function resolveChatReport({id}){await ownerOnly();requireThat(typeof id==='string'&&!id.includes('/'),'Invalid report ID.');await updateDoc(doc(db,'sparkReports',id),{status:'resolved'});}
async function paymentRequest(path){const endpoint=billingApiURL(cached?.billing.apiUrl);requireThat(endpoint,'Automatic subscriptions are not connected yet.');const token=await auth.currentUser.getIdToken();const response=await fetch(endpoint+path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(70000)});const result=await response.json().catch(()=>({error:'Payment server is starting or unavailable. Try again shortly.'}));requireThat(response.ok&&!result.error,result.error||'Payment service unavailable. Try again shortly.');return result;}
async function createCheckout(){uid();return paymentRequest('/checkout');}
async function refreshPayment(){uid();if(cached?.billing.apiUrl)return paymentRequest('/refresh');return {status:'NOT_CONFIGURED'};}

async function requestMembership({reference,payerEmail}){const me=uid();safeText(reference,3,200);safeText(payerEmail,3,254);requireThat(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payerEmail),'Enter the email used for PayPal.');await setDoc(doc(db,'sparkMembershipRequests',me),{uid:me,reference,payerEmail,accountEmail:auth.currentUser.email||'',status:'pending',updatedAt:serverTimestamp()});}
async function saveMembership({uid:player,...fields}){const owner=await ownerOnly();idCheck(player);const clean=cleanMembership(fields);await runTransaction(db,async tx=>{const pref=playerRef(player),req=doc(db,'sparkMembershipRequests',player);const [profile,request]=await Promise.all([tx.get(pref),tx.get(req)]);requireThat(profile.exists(),'No player has this UID. Copy it from a payment request or Firebase Authentication.');tx.set(doc(db,'sparkMemberships',player),{...clean,checkedBy:owner,checkedAt:serverTimestamp()});if(request.exists())tx.update(req,{status:clean.active?'reviewed':'revoked'});});}

async function saveBilling({apiUrl,offerLabel,requireMembership}){await ownerOnly();requireThat(typeof requireMembership==='boolean','Choose the membership setting.');await setDoc(doc(db,'sparkConfig','billing'),{paypalUrl:'',apiUrl:billingApiURL(apiUrl),offerLabel:safeText(offerLabel,1,100),requireMembership});}
// Direct Firestore operations only. This dispatcher is not a Firebase callable Function.
async function saveTester({uid:player,...fields}){const owner=await ownerOnly();idCheck(player);const clean=cleanTester(fields);requireThat((await getDoc(playerRef(player))).exists(),'Ask the tester to create an account and open the game first, then copy their Player ID.');await setDoc(doc(db,'sparkTesters',player),{...clean,checkedBy:owner,checkedAt:serverTimestamp()});}
async function loadBank(){return rows(await getDocs(collection(db,'sparkPlayers',uid(),'bank'))).map(item=>({...item,image:item.image?.toUint8Array()}));}
async function saveBankItem(fields){const clean=cleanBankItem(fields),items=await loadBank(),id=freeBankSlot(items,clean.kind),ref=doc(db,'sparkPlayers',uid(),'bank',id),capacity=doc(db,'sparkBankCapacity','global');await runTransaction(db,async tx=>{const [slot,quota]=await Promise.all([tx.get(ref),tx.get(capacity)]);requireThat(!slot.exists(),'Inventory changed on another device. Refresh and try again.');const used=quota.data()?.used||0;requireThat(used<400,'Game storage is full. Save this item to your phone or device instead.');tx.set(ref,{...clean,...(clean.image?{image:Bytes.fromUint8Array(clean.image)}:{}),savedAt:serverTimestamp()});tx.set(capacity,{used:used+1,lastSlot:id,operation:'create',updatedAt:serverTimestamp()});});return {id};}
async function deleteBankItem({id,expectedSavedAt}){requireThat(/^(image-(?:[0-9]|1[01])|note-(?:[0-9]|1[0-9]|2[0-3]))$/.test(id),'Invalid inventory slot');const ref=doc(db,'sparkPlayers',uid(),'bank',id),capacity=doc(db,'sparkBankCapacity','global');await runTransaction(db,async tx=>{const [slot,quota]=await Promise.all([tx.get(ref),tx.get(capacity)]);if(!slot.exists())return;if(expectedSavedAt!==undefined)requireThat(slot.data().savedAt?.toMillis()===expectedSavedAt,'An item changed after your download. Download the bank again before clearing it.');requireThat(quota.exists()&&quota.data().used>0,'Storage counter needs owner attention. Your item has not been removed.');tx.delete(ref);tx.set(capacity,{used:quota.data().used-1,lastSlot:id,operation:'delete',updatedAt:serverTimestamp()});});}
const actions={loadBank,saveBankItem,deleteBankItem,refreshPayment,saveTester,getPlayer,gameAction,submitProof,askGuide,battle,reviewQueue,reviewProof,getAdminOverview,saveAnnouncement,sendChat,reportChat,moderateChat,getChatReports,resolveChatReport,createCheckout,requestMembership,saveMembership,saveBilling};
export async function call(name,payload){uid();requireThat(actions[name],'Unknown operation.');return actions[name](payload);}
