// Run with: pnpm test:rules (requires a local Firestore emulator and Java).
import {before,after,beforeEach,test} from 'node:test';import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc,updateDoc,writeBatch,serverTimestamp,Timestamp,Bytes} from 'firebase/firestore';
let env;
const db=uid=>env.authenticatedContext(uid,{email:uid+'@example.test'}).firestore();
const profile={name:'Alice',path:'Service',avatar:'Compass',business:''};
const stage=(n=1)=>({step:n,status:'active',draft:n>=3?'A'.repeat(70):'',proofId:'',feedback:'',practiceAnswer:n>=2?1:-1,updatedAt:serverTimestamp()});
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-oyo-unlocked',firestore:{rules:readFileSync('firestore.rules','utf8')}});});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'sparkConfig/owner'),{uid:'owner'});await setDoc(doc(c.firestore(),'sparkPlayers/alice'),{profile,email:'alice@example.test',cosmetics:{},updatedAt:Timestamp.now()});});});
after(async()=>env?.cleanup());
test('owner cannot be self-appointed, even through forged claims',async()=>{await assertFails(setDoc(doc(db('alice'),'sparkConfig/owner'),{uid:'alice'}));await assertFails(setDoc(doc(env.authenticatedContext('bob',{owner:true}).firestore(),'sparkMemberships/bob'),{active:true,expiresAt:Date.now()+86400000}));});
test('own profile is editable but cross-user reads and arbitrary XP are denied',async()=>{await assertSucceeds(updateDoc(doc(db('alice'),'sparkPlayers/alice'),{profile:{...profile,name:'New name'},updatedAt:serverTimestamp()}));await assertFails(getDoc(doc(db('bob'),'sparkPlayers/alice')));await assertFails(updateDoc(doc(db('alice'),'sparkPlayers/alice'),{xp:999999,updatedAt:serverTimestamp()}));});
test('only the first mission starts, and quiz answers cannot be bypassed',async()=>{const a=db('alice');await assertSucceeds(setDoc(doc(a,'sparkPlayers/alice/missions/m1'),stage()));await assertFails(setDoc(doc(a,'sparkPlayers/alice/missions/m2'),stage()));await assertFails(updateDoc(doc(a,'sparkPlayers/alice/missions/m1'),{step:2,practiceAnswer:0,updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(a,'sparkPlayers/alice/missions/m1'),{step:2,practiceAnswer:1,updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(a,'sparkPlayers/alice/missions/m1'),{status:'verified',step:6,updatedAt:serverTimestamp()}));});
async function pending(){await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'sparkPlayers/alice/missions/m1'),stage(4));});const a=db('alice'),batch=writeBatch(a);batch.set(doc(a,'sparkProofs/proof1'),{uid:'alice',missionId:'m1',summary:'A'.repeat(70),evidence:['B'.repeat(25),'C'.repeat(25),'D'.repeat(25)],url:'https://example.test/proof',status:'pending',feedback:'',createdAt:serverTimestamp()});batch.update(doc(a,'sparkPlayers/alice/missions/m1'),{step:5,status:'pending',proofId:'proof1',updatedAt:serverTimestamp()});return assertSucceeds(batch.commit());}
test('text proof requires an atomic submission and only owner review advances it',async()=>{await pending();await assertFails(updateDoc(doc(db('alice'),'sparkProofs/proof1'),{status:'verified'}));const o=db('owner'),b=writeBatch(o);b.update(doc(o,'sparkProofs/proof1'),{status:'verified',feedback:'Evidence meets all criteria.',reviewer:'owner',reviewedAt:serverTimestamp()});b.update(doc(o,'sparkPlayers/alice/missions/m1'),{step:6,status:'verified',feedback:'Evidence meets all criteria.',updatedAt:serverTimestamp()});await assertSucceeds(b.commit());await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m2'),stage()));});
test('private evidence is invisible to other players and anonymous callers',async()=>{await pending();await assertSucceeds(getDoc(doc(db('alice'),'sparkProofs/proof1')));await assertFails(getDoc(doc(db('bob'),'sparkProofs/proof1')));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'sparkProofs/proof1')));});
test('membership requests never grant access and only owner writes an expiry',async()=>{const a=db('alice');await assertSucceeds(setDoc(doc(a,'sparkMembershipRequests/alice'),{uid:'alice',reference:'I-REFERENCE',payerEmail:'payer@example.test',accountEmail:'alice@example.test',status:'pending',updatedAt:serverTimestamp()}));const member={active:true,expiresAt:Date.now()+86400000,reference:'I-REFERENCE',note:'Checked in PayPal',checkedBy:'owner',checkedAt:serverTimestamp()};await assertFails(setDoc(doc(a,'sparkMemberships/alice'),member));await assertSucceeds(setDoc(doc(db('owner'),'sparkMemberships/alice'),member));await assertFails(getDoc(doc(db('bob'),'sparkMembershipRequests/alice')));});
test('paid world writes reject expired access and allow a valid owner grant',async()=>{await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'sparkPlayers/alice/bosses/foundation'),{won:true,round:3});await setDoc(doc(c.firestore(),'sparkMemberships/alice'),{active:true,expiresAt:Date.now()-1000});});await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));await setDoc(doc(db('owner'),'sparkMemberships/alice'),{active:true,expiresAt:Date.now()+86400000,reference:'I-123',note:'',checkedBy:'owner',checkedAt:serverTimestamp()});await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));});
test('boss victories cannot skip proof gates or rounds',async()=>{const b={round:3,attempts:1,won:true,history:[],lastChoice:'clarify',lastCheck:'observation',lastAnswer:'A'.repeat(50),updatedAt:serverTimestamp()};await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/bosses/foundation'),b));await env.withSecurityRulesDisabled(async c=>{for(const id of ['m1','m2'])await setDoc(doc(c.firestore(),'sparkPlayers/alice/missions/'+id),{...stage(6),status:'verified'});});await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/bosses/foundation'),b));await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/bosses/foundation'),{...b,round:1,won:false}));});
test('chat requires own identity and a rate-limit write, and rejects rapid repeat',async()=>{const a=db('alice'),msg=id=>({uid:'alice',playerName:'Alice',text:'Hello community',removed:false,createdAt:serverTimestamp()});await assertFails(setDoc(doc(a,'sparkChat/one'),msg()));const b=writeBatch(a);b.set(doc(a,'sparkChat/one'),msg());b.set(doc(a,'sparkChatLimits/alice'),{sentAt:serverTimestamp(),messageId:'one'});await assertSucceeds(b.commit());const repeat=writeBatch(a);repeat.set(doc(a,'sparkChat/two'),msg());repeat.set(doc(a,'sparkChatLimits/alice'),{sentAt:serverTimestamp(),messageId:'two'});await assertFails(repeat.commit());await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'sparkChat/one')));});
test('only registered owner can change resources and PayPal settings',async()=>{await assertFails(setDoc(doc(db('alice'),'appConfig/resources'),{mainUrl:'https://example.test'}));await assertFails(setDoc(doc(db('alice'),'sparkConfig/billing'),{requireMembership:false,offerLabel:'Free',paypalUrl:''}));await assertSucceeds(setDoc(doc(db('owner'),'sparkConfig/billing'),{requireMembership:true,offerLabel:'Subscribe',paypalUrl:'https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-123'}));});

const testerGrant=(active=true,expiresAt=0)=>({active,expiresAt,note:'Tester',checkedBy:'owner',checkedAt:serverTimestamp()});
async function openBrand(){await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'sparkPlayers/alice/bosses/foundation'),{won:true,round:3}));}
test('tester grants are owner only and private to that player',async()=>{await assertFails(setDoc(doc(db('alice'),'sparkTesters/alice'),testerGrant()));await assertSucceeds(setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant()));await assertSucceeds(getDoc(doc(db('alice'),'sparkTesters/alice')));await assertFails(getDoc(doc(db('bob'),'sparkTesters/alice')));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'sparkTesters/alice')));});
test('indefinite tester opens paid gates but cannot bypass progression',async()=>{await setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant());await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));await openBrand();await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));});
test('expired tester cannot start paid world and invalid owner dates are denied',async()=>{await openBrand();await assertFails(setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant(true,Date.now()-1000)));await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'sparkTesters/alice'),testerGrant(true,Date.now()-1000)));await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));});
test('tester revocation preserves saved progress and separately paid access',async()=>{await openBrand();await setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant(true,Date.now()+86400000));await setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant(false));await assertSucceeds(getDoc(doc(db('alice'),'sparkPlayers/alice/bosses/foundation')));await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));await setDoc(doc(db('owner'),'sparkMemberships/alice'),{active:true,expiresAt:Date.now()+86400000,reference:'I-123',note:'',checkedBy:'owner',checkedAt:serverTimestamp()});await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));});

test('automatic membership and server bindings cannot be written by player or owner clients',async()=>{for(const user of ['alice','owner'])for(const path of ['sparkPayPalMemberships/alice','sparkBillingPlayers/alice','sparkBillingSubscriptions/I-123','sparkBillingEvents/EV-1','sparkBillingSales/SALE-1','sparkBillingLocks/user-alice'])await assertFails(setDoc(doc(db(user),path),{active:true,expiresAt:Date.now()+86400000}));});
test('server automatic access opens paid gate and tester revocation cannot remove it',async()=>{await openBrand();await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'sparkPayPalMemberships/alice'),{active:true,expiresAt:Date.now()+86400000}));await setDoc(doc(db('owner'),'sparkTesters/alice'),testerGrant(false));await assertSucceeds(setDoc(doc(db('alice'),'sparkPlayers/alice/missions/m3'),stage()));await assertFails(getDoc(doc(db('bob'),'sparkPayPalMemberships/alice')));});

const bankNote=()=>({kind:'note',title:'Field note',text:'Keep this evidence',savedAt:serverTimestamp()});
async function bankCreate(user,id='note-0',used=1,value=bankNote()){const d=db(user),batch=writeBatch(d);batch.set(doc(d,'sparkPlayers/'+user+'/bank/'+id),value);batch.set(doc(d,'sparkBankCapacity/global'),{used,lastSlot:id,operation:'create',updatedAt:serverTimestamp()});return batch.commit();}
test('bank create requires an atomic capacity increment and stays private',async()=>{await assertFails(setDoc(doc(db('alice'),'sparkPlayers/alice/bank/note-0'),bankNote()));await assertSucceeds(bankCreate('alice'));await assertFails(getDoc(doc(db('bob'),'sparkPlayers/alice/bank/note-0')));await assertFails(getDoc(doc(db('owner'),'sparkPlayers/alice/bank/note-0')));await assertFails(setDoc(doc(db('alice'),'sparkBankCapacity/global'),{used:0,lastSlot:'note-0',operation:'delete',updatedAt:serverTimestamp()}));});
test('bank full cap, slot bounds and oversized screenshots are denied',async()=>{await assertFails(bankCreate('alice','note-24'));await assertFails(bankCreate('alice','image-0',1,{kind:'screenshot',title:'Large',text:'',mime:'image/jpeg',image:Bytes.fromUint8Array(new Uint8Array(180001)),savedAt:serverTimestamp()}));await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),'sparkBankCapacity/global'),{used:400}));await assertFails(bankCreate('alice','note-0',401));});
test('bank offload atomically frees a slot and cannot remove mission progress',async()=>{await assertSucceeds(bankCreate('alice'));const d=db('alice'),batch=writeBatch(d);batch.delete(doc(d,'sparkPlayers/alice/bank/note-0'));batch.set(doc(d,'sparkBankCapacity/global'),{used:0,lastSlot:'note-0',operation:'delete',updatedAt:serverTimestamp()});await assertSucceeds(batch.commit());await assertSucceeds(bankCreate('alice'));await assertFails(setDoc(doc(d,'sparkPlayers/alice/bank/note-0'),bankNote()));});
