import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {verifiedAccess,periodEnd,fixedPlan} from '../policy.mjs';
import {createService} from '../service.mjs';
import {createHandler} from '../http.mjs';
import {createPayPal} from '../paypal.mjs';
const now=Date.parse('2026-09-18T12:00:00Z');
const price={value:'20.00',currency_code:'CAD'};
const plan={status:'ACTIVE',billing_cycles:[{tenure_type:'REGULAR',total_cycles:0,frequency:{interval_unit:'MONTH',interval_count:1},pricing_scheme:{fixed_price:price}}]};
const sub={id:'I-123',custom_id:'alice',plan_id:'P-123',status:'ACTIVE',billing_info:{last_payment:{amount:price,time:'2026-09-18T10:00:00Z'},next_billing_time:'2026-10-18T10:00:00Z'},links:[{rel:'approve',href:'https://www.sandbox.paypal.com/approve?ba_token=test'}]};
const transaction={id:'SALE-123',status:'COMPLETED',time:'2026-09-18T10:00:00Z',amount_with_breakdown:{gross_amount:price}};
const access=(extra={})=>verifiedAccess({subscription:sub,plan,transactions:[transaction],uid:'alice',planId:'P-123',now,...extra});
test('matching completed payment activates only its paid period',()=>{const a=access();assert.equal(a.active,true);assert.equal(a.expiresAt,Date.parse('2026-10-18T10:00:00Z'));assert.equal(access({now:a.expiresAt}).active,false);});
test('approval, return claims and future billing dates alone grant nothing',()=>{assert.equal(access({transactions:[]}).active,false);assert.equal(access({subscription:{...sub,status:'APPROVED'}}).active,false);assert.equal(access({subscription:{...sub,billing_info:{next_billing_time:'2030-01-01T00:00:00Z'}}}).active,false);});
test('payment must match owner plan, player, currency, amount and completed status',()=>{assert.throws(()=>access({uid:'bob'}));assert.throws(()=>access({planId:'P-OTHER'}));for(const t of [{...transaction,status:'PENDING'},{...transaction,amount_with_breakdown:{gross_amount:{...price,value:'1.00'}}},{...transaction,amount_with_breakdown:{gross_amount:{...price,currency_code:'USD'}}}])assert.equal(access({transactions:[t]}).active,false);});
test('trial, setup fees, quantity and plan overrides are rejected',()=>{assert.throws(()=>fixedPlan({...plan,billing_cycles:[...plan.billing_cycles,{tenure_type:'TRIAL'}]}));assert.throws(()=>fixedPlan({...plan,payment_preferences:{setup_fee:price}}));assert.throws(()=>access({subscription:{...sub,plan_overridden:true}}));assert.throws(()=>access({subscription:{...sub,quantity:'2'}}));});
test('cancellation preserves paid time and refunds fail closed',()=>{assert.equal(access({subscription:{...sub,status:'CANCELLED'}}).active,true);assert.equal(access({held:true}).active,false);assert.equal(access({held:true}).status,'PAYMENT_REVIEW');});
test('calendar periods clamp month-end and leap-day anniversaries',()=>{assert.equal(periodEnd(Date.parse('2026-01-31T10:00:00Z'),{interval_unit:'MONTH',interval_count:1}),Date.parse('2026-02-28T10:00:00Z'));assert.equal(periodEnd(Date.parse('2024-02-29T10:00:00Z'),{interval_unit:'YEAR',interval_count:1}),Date.parse('2025-02-28T10:00:00Z'));});
test('a future billing date cannot extend beyond a completed payment period',()=>{assert.equal(access({subscription:{...sub,billing_info:{...sub.billing_info,next_billing_time:'2030-01-01T00:00:00Z'}}}).expiresAt,access().expiresAt);});
function fixture(){
  const map=new Map([['sparkPlayers/alice',{profile:{name:'Alice'}}],['sparkPlayers/alice/missions/m1',{status:'verified'}],['sparkMemberships/alice',{active:true,expiresAt:now+9999}],['sparkTesters/alice',{active:true,expiresAt:0}],['sparkBillingPlayers/alice',{subscriptionId:'I-123'}],['sparkBillingSubscriptions/I-123',{uid:'alice',held:false}]]);
  const writes=[],snap=key=>({exists:map.has(key),data:()=>structuredClone(map.get(key))});
  const tx={get:async r=>snap(r.key),set:(r,v)=>{writes.push(r.key);map.set(r.key,structuredClone(v));},delete:r=>map.delete(r.key)};
  const db={collection:c=>({doc:id=>({key:c+'/'+id,get:async()=>snap(c+'/'+id)})}),runTransaction:async f=>f(tx)};
  let current=structuredClone(sub),transactions=[structuredClone(transaction)],verified=true,creates=0;
  const paypal={verify:async()=>{if(!verified)throw Error('Bad signature');},subscription:async()=>current,plan:async()=>plan,transactions:async()=>transactions,create:async()=>{creates++;return {...current,status:'APPROVAL_PENDING'};}};
  const service=createService({db,paypal,config:{mode:'sandbox',planId:'P-123'},clock:()=>now});
  return {map,writes,service,setSub:s=>current=s,setTransactions:t=>transactions=t,badSignature:()=>verified=false,creates:()=>creates};
}
const event=(id='EV-1',type='PAYMENT.SALE.COMPLETED')=>({id,event_type:type,resource:{id:'SALE-123',billing_agreement_id:'I-123'}});
test('verified webhook writes automatic access and preserves tester, manual access and progress',async()=>{const f=fixture();await f.service.webhook({},event());assert.equal(f.map.get('sparkPayPalMemberships/alice').active,true);assert.equal(f.map.get('sparkTesters/alice').active,true);assert.equal(f.map.get('sparkMemberships/alice').expiresAt,now+9999);assert.equal(f.map.get('sparkPlayers/alice/missions/m1').status,'verified');assert.ok(f.writes.every(k=>!k.startsWith('sparkPlayers/')&&!k.startsWith('sparkTesters/')&&!k.startsWith('sparkMemberships/')));});
test('duplicate webhook does not award or extend a second time',async()=>{const f=fixture();await f.service.webhook({},event());const count=f.writes.length;assert.equal((await f.service.webhook({},event())).duplicate,true);assert.equal(f.writes.length,count+1);});
test('renewal verifies a new payment and moves the paid-through date',async()=>{const f=fixture();await f.service.webhook({},event());const old=f.map.get('sparkPayPalMemberships/alice').expiresAt;f.setSub({...sub,billing_info:{last_payment:{amount:price,time:'2026-09-18T11:00:00Z'},next_billing_time:'2026-10-18T11:00:00Z'}});f.setTransactions([{...transaction,id:'SALE-NEW',time:'2026-09-18T11:00:00Z'}]);await f.service.webhook({},event('EV-2'));assert.ok(f.map.get('sparkPayPalMemberships/alice').expiresAt>old);});
test('refund holds access; a late completed event cannot reactivate it',async()=>{const f=fixture();await f.service.webhook({},event());await f.service.webhook({},event('EV-REFUND','PAYMENT.SALE.REFUNDED'));await f.service.webhook({},event('EV-LATE'));assert.equal(f.map.get('sparkPayPalMemberships/alice').active,false);assert.equal(f.map.get('sparkBillingSubscriptions/I-123').held,true);});
test('refund without subscription ID resolves through recorded sale',async()=>{const f=fixture();await f.service.webhook({},event());await f.service.webhook({},{id:'REFUND',event_type:'PAYMENT.SALE.REFUNDED',resource:{id:'REFUND-123',sale_id:'SALE-123'}});assert.equal(f.map.get('sparkPayPalMemberships/alice').active,false);});
test('failed signature makes no database changes',async()=>{const f=fixture();f.badSignature();await assert.rejects(f.service.webhook({},event()));assert.equal(f.writes.length,0);});
test('late events for replaced subscription do not overwrite current access',async()=>{const f=fixture();f.map.set('sparkBillingPlayers/alice',{subscriptionId:'I-NEW'});f.map.set('sparkPayPalMemberships/alice',{active:true,subscriptionId:'I-NEW'});await f.service.webhook({},event());assert.equal(f.map.get('sparkPayPalMemberships/alice').subscriptionId,'I-NEW');});
test('checkout rejects an existing active subscription and reuses pending approval',async()=>{const f=fixture();await assert.rejects(f.service.checkout('alice'),/already have/);f.setSub({...sub,status:'APPROVAL_PENDING'});assert.match((await f.service.checkout('alice')).url,/sandbox.paypal.com/);assert.equal(f.creates(),0);});
test('new checkout binds authenticated player on the server',async()=>{const f=fixture();f.map.delete('sparkBillingPlayers/alice');await f.service.checkout('alice');assert.equal(f.creates(),1);assert.equal(f.map.get('sparkBillingSubscriptions/I-123').uid,'alice');});
test('uncertain checkout older than one hour cannot create a duplicate',async()=>{const f=fixture();f.map.set('sparkBillingPlayers/alice',{requestId:'old',createdAt:now-3600001});await assert.rejects(f.service.checkout('alice'),/investigation/);assert.equal(f.creates(),0);});
async function request({origin='https://game.test',token='good',path='/checkout',body='{}'}={}){
  let called;const handler=createHandler({origin:'https://game.test',auth:{verifyIdToken:async t=>{if(t!=='good')throw Error();return {uid:'alice'};}},service:{checkout:async uid=>{called=uid;return {url:'https://www.paypal.com/'};}}});
  const req=Readable.from([body]);Object.assign(req,{url:path,method:'POST',headers:{origin,authorization:'Bearer '+token}});let status,result;await handler(req,{writeHead:s=>status=s,end:s=>result=s});return {status,result,called};
}
test('HTTP checkout trusts Firebase identity, never a body-supplied UID',async()=>{const r=await request({body:'{"uid":"bob"}'});assert.equal(r.status,200);assert.equal(r.called,'alice');});
test('HTTP rejects foreign origin and bad credentials',async()=>{assert.equal((await request({origin:'https://evil.test'})).status,403);assert.equal((await request({token:'bad'})).status,401);});
test('HTTP rejects malformed and oversized bodies',async()=>{assert.equal((await request({body:'{'})).status,400);assert.equal((await request({body:'a'.repeat(131073)})).status,413);});
test('PayPal signature response must explicitly succeed',async()=>{const responses=[{access_token:'token',expires_in:3600},{verification_status:'FAILURE'}],calls=[];const paypal=createPayPal({mode:'sandbox',clientId:'id',secret:'secret',webhookId:'WH'},async(url,options)=>{calls.push({url,options});return {ok:true,status:200,json:async()=>responses.shift()};});await assert.rejects(paypal.verify({'paypal-auth-algo':'SHA256withRSA','paypal-cert-url':'https://api.paypal.com/cert','paypal-transmission-id':'T','paypal-transmission-sig':'S','paypal-transmission-time':'date'},event()),/Invalid PayPal signature/);assert.equal(JSON.parse(calls[1].options.body).webhook_id,'WH');assert.ok(calls.every(c=>c.url.startsWith('https://api-m.sandbox.paypal.com/')));});
